import 'package:flutter/material.dart';

@immutable
class AppTextTheme extends ThemeExtension<AppTextTheme> {
  final TextStyle? h1Bold;
  final TextStyle? h2Bold;
  final TextStyle? h3Bold;
  final TextStyle? h4Bold;
  final TextStyle? h5Bold;
  final TextStyle? h6Bold;
  final TextStyle? bodyXlargeRegular;
  final TextStyle? bodyXlargeSemibold;
  final TextStyle? bodyXlargeBold;
  final TextStyle? bodyXlargeMedium;
  final TextStyle? bodyLargeRegular;
  final TextStyle? bodyLargeSemibold;
  final TextStyle? bodyLargeBold;
  final TextStyle? bodyLargeMedium;
  final TextStyle? bodyMediumRegular;
  final TextStyle? bodyMediumSemibold;
  final TextStyle? bodyMediumBold;
  final TextStyle? bodyMediumMedium;
  final TextStyle? bodySmallRegular;
  final TextStyle? bodySmallSemibold;
  final TextStyle? bodySmallBold;
  final TextStyle? bodySmallMedium;
  final TextStyle? bodyXsmallRegular;
  final TextStyle? bodyXsmallSemibold;
  final TextStyle? bodyXsmallBold;
  final TextStyle? bodyXsmallMedium;
  final TextStyle? materialThemeDisplayLarge;
  final TextStyle? materialThemeDisplayMedium;
  final TextStyle? materialThemeDisplaySmall;
  final TextStyle? materialThemeHeadlineLarge;
  final TextStyle? materialThemeHeadlineMedium;
  final TextStyle? materialThemeHeadlineSmall;
  final TextStyle? materialThemeBodyLarge;
  final TextStyle? materialThemeBodyMedium;
  final TextStyle? materialThemeBodySmall;
  final TextStyle? materialThemeLabelLarge;
  final TextStyle? materialThemeLabelMedium;
  final TextStyle? materialThemeLabelSmall;
  final TextStyle? materialThemeTitleLarge;
  final TextStyle? materialThemeTitleMedium;
  final TextStyle? materialThemeTitleSmall;

   const AppTextTheme({
    this.h1Bold,
    this.h2Bold,
    this.h3Bold,
    this.h4Bold,
    this.h5Bold,
    this.h6Bold,
    this.bodyXlargeRegular,
    this.bodyXlargeSemibold,
    this.bodyXlargeBold,
    this.bodyXlargeMedium,
    this.bodyLargeRegular,
    this.bodyLargeSemibold,
    this.bodyLargeBold,
    this.bodyLargeMedium,
    this.bodyMediumRegular,
    this.bodyMediumSemibold,
    this.bodyMediumBold,
    this.bodyMediumMedium,
    this.bodySmallRegular,
    this.bodySmallSemibold,
    this.bodySmallBold,
    this.bodySmallMedium,
    this.bodyXsmallRegular,
    this.bodyXsmallSemibold,
    this.bodyXsmallBold,
    this.bodyXsmallMedium,
    this.materialThemeDisplayLarge,
    this.materialThemeDisplayMedium,
    this.materialThemeDisplaySmall,
    this.materialThemeHeadlineLarge,
    this.materialThemeHeadlineMedium,
    this.materialThemeHeadlineSmall,
    this.materialThemeBodyLarge,
    this.materialThemeBodyMedium,
    this.materialThemeBodySmall,
    this.materialThemeLabelLarge,
    this.materialThemeLabelMedium,
    this.materialThemeLabelSmall,
    this.materialThemeTitleLarge,
    this.materialThemeTitleMedium,
    this.materialThemeTitleSmall, 
  });

  const AppTextTheme.fallback()
      : this(
        h1Bold: const TextStyle(
          fontSize: 48,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 2.5,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        h2Bold: const TextStyle(
          fontSize: 40,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 3,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        h3Bold: const TextStyle(
          fontSize: 32,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 3.75,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        h4Bold: const TextStyle(
          fontSize: 24,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 5,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        h5Bold: const TextStyle(
          fontSize: 20,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 6,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        h6Bold: const TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 6.67,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyXlargeRegular: const TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.w400,
          fontFamily: "Urbanist",
          height: 7.78,
          letterSpacing: 0.04,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyXlargeSemibold: const TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 7.78,
          letterSpacing: 0.04,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyXlargeBold: const TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 7.78,
          letterSpacing: 0.04,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyXlargeMedium: const TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.w500,
          fontFamily: "Urbanist",
          height: 7.78,
          letterSpacing: 0.04,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyLargeRegular: const TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w400,
          fontFamily: "Urbanist",
          height: 8.75,
          letterSpacing: 0.03,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyLargeSemibold: const TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 8.75,
          letterSpacing: 0.03,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyLargeBold: const TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 8.75,
          letterSpacing: 0.03,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyLargeMedium: const TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w500,
          fontFamily: "Urbanist",
          height: 8.75,
          letterSpacing: 0.03,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyMediumRegular: const TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w400,
          fontFamily: "Urbanist",
          height: 10,
          letterSpacing: 0.03,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyMediumSemibold: const TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 10,
          letterSpacing: 0.03,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyMediumBold: const TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          height: 10,
          letterSpacing: 0.03,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyMediumMedium: const TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w500,
          fontFamily: "Urbanist",
          height: 10,
          letterSpacing: 0.03,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodySmallRegular: const TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w400,
          fontFamily: "Urbanist",
          letterSpacing: 0.02,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodySmallSemibold: const TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w500,
          fontFamily: "Urbanist",
          letterSpacing: 0.02,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodySmallBold: const TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          letterSpacing: 0.02,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodySmallMedium: const TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w500,
          fontFamily: "Urbanist",
          letterSpacing: 0.02,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyXsmallRegular: const TextStyle(
          fontSize: 10,
          fontWeight: FontWeight.w400,
          fontFamily: "Urbanist",
          letterSpacing: 0.02,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyXsmallSemibold: const TextStyle(
          fontSize: 10,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          letterSpacing: 0.02,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyXsmallBold: const TextStyle(
          fontSize: 10,
          fontWeight: FontWeight.w700,
          fontFamily: "Urbanist",
          letterSpacing: 0.02,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        bodyXsmallMedium: const TextStyle(
          fontSize: 10,
          fontWeight: FontWeight.w500,
          fontFamily: "Urbanist",
          letterSpacing: 0.02,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeDisplayLarge: const TextStyle(
          fontSize: 57,
          fontWeight: FontWeight.w400,
          fontFamily: "Roboto",
          height: 1.12,
          letterSpacing: -0.14,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeDisplayMedium: const TextStyle(
          fontSize: 45,
          fontWeight: FontWeight.w400,
          fontFamily: "Roboto",
          height: 1.16,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeDisplaySmall: const TextStyle(
          fontSize: 36,
          fontWeight: FontWeight.w400,
          fontFamily: "Roboto",
          height: 1.22,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeHeadlineLarge: const TextStyle(
          fontSize: 32,
          fontWeight: FontWeight.w400,
          fontFamily: "Roboto",
          height: 1.25,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeHeadlineMedium: const TextStyle(
          fontSize: 28,
          fontWeight: FontWeight.w400,
          fontFamily: "Roboto",
          height: 1.29,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeHeadlineSmall: const TextStyle(
          fontSize: 24,
          fontWeight: FontWeight.w400,
          fontFamily: "Roboto",
          height: 1.33,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeBodyLarge: const TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w400,
          fontFamily: "Roboto",
          height: 1.5,
          letterSpacing: 0.08,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeBodyMedium: const TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w400,
          fontFamily: "Roboto",
          height: 1.43,
          letterSpacing: 0.04,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeBodySmall: const TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w400,
          fontFamily: "Roboto",
          height: 1.33,
          letterSpacing: 0.05,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeLabelLarge: const TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w500,
          fontFamily: "Roboto",
          height: 1.43,
          letterSpacing: 0.01,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeLabelMedium: const TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w500,
          fontFamily: "Roboto",
          height: 1.33,
          letterSpacing: 0.06,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeLabelSmall: const TextStyle(
          fontSize: 11,
          fontWeight: FontWeight.w500,
          fontFamily: "Roboto",
          height: 1.45,
          letterSpacing: 0.06,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeTitleLarge: const TextStyle(
          fontSize: 22,
          fontWeight: FontWeight.w400,
          fontFamily: "Roboto",
          height: 1.27,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeTitleMedium: const TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w500,
          fontFamily: "Roboto",
          height: 1.5,
          letterSpacing: 0.02,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
        materialThemeTitleSmall: const TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w500,
          fontFamily: "Roboto",
          height: 1.43,
          letterSpacing: 0.01,
          fontStyle: FontStyle.normal,
          decoration: TextDecoration.none,
        ),
      );

  @override
  AppTextTheme copyWith({
    TextStyle? h1Bold,
    TextStyle? h2Bold,
    TextStyle? h3Bold,
    TextStyle? h4Bold,
    TextStyle? h5Bold,
    TextStyle? h6Bold,
    TextStyle? bodyXlargeRegular,
    TextStyle? bodyXlargeSemibold,
    TextStyle? bodyXlargeBold,
    TextStyle? bodyXlargeMedium,
    TextStyle? bodyLargeRegular,
    TextStyle? bodyLargeSemibold,
    TextStyle? bodyLargeBold,
    TextStyle? bodyLargeMedium,
    TextStyle? bodyMediumRegular,
    TextStyle? bodyMediumSemibold,
    TextStyle? bodyMediumBold,
    TextStyle? bodyMediumMedium,
    TextStyle? bodySmallRegular,
    TextStyle? bodySmallSemibold,
    TextStyle? bodySmallBold,
    TextStyle? bodySmallMedium,
    TextStyle? bodyXsmallRegular,
    TextStyle? bodyXsmallSemibold,
    TextStyle? bodyXsmallBold,
    TextStyle? bodyXsmallMedium,
    TextStyle? materialThemeDisplayLarge,
    TextStyle? materialThemeDisplayMedium,
    TextStyle? materialThemeDisplaySmall,
    TextStyle? materialThemeHeadlineLarge,
    TextStyle? materialThemeHeadlineMedium,
    TextStyle? materialThemeHeadlineSmall,
    TextStyle? materialThemeBodyLarge,
    TextStyle? materialThemeBodyMedium,
    TextStyle? materialThemeBodySmall,
    TextStyle? materialThemeLabelLarge,
    TextStyle? materialThemeLabelMedium,
    TextStyle? materialThemeLabelSmall,
    TextStyle? materialThemeTitleLarge,
    TextStyle? materialThemeTitleMedium,
    TextStyle? materialThemeTitleSmall,
  }) {
    return AppTextTheme(
      h1Bold: h1Bold ?? this.h1Bold,
      h2Bold: h2Bold ?? this.h2Bold,
      h3Bold: h3Bold ?? this.h3Bold,
      h4Bold: h4Bold ?? this.h4Bold,
      h5Bold: h5Bold ?? this.h5Bold,
      h6Bold: h6Bold ?? this.h6Bold,
      bodyXlargeRegular: bodyXlargeRegular ?? this.bodyXlargeRegular,
      bodyXlargeSemibold: bodyXlargeSemibold ?? this.bodyXlargeSemibold,
      bodyXlargeBold: bodyXlargeBold ?? this.bodyXlargeBold,
      bodyXlargeMedium: bodyXlargeMedium ?? this.bodyXlargeMedium,
      bodyLargeRegular: bodyLargeRegular ?? this.bodyLargeRegular,
      bodyLargeSemibold: bodyLargeSemibold ?? this.bodyLargeSemibold,
      bodyLargeBold: bodyLargeBold ?? this.bodyLargeBold,
      bodyLargeMedium: bodyLargeMedium ?? this.bodyLargeMedium,
      bodyMediumRegular: bodyMediumRegular ?? this.bodyMediumRegular,
      bodyMediumSemibold: bodyMediumSemibold ?? this.bodyMediumSemibold,
      bodyMediumBold: bodyMediumBold ?? this.bodyMediumBold,
      bodyMediumMedium: bodyMediumMedium ?? this.bodyMediumMedium,
      bodySmallRegular: bodySmallRegular ?? this.bodySmallRegular,
      bodySmallSemibold: bodySmallSemibold ?? this.bodySmallSemibold,
      bodySmallBold: bodySmallBold ?? this.bodySmallBold,
      bodySmallMedium: bodySmallMedium ?? this.bodySmallMedium,
      bodyXsmallRegular: bodyXsmallRegular ?? this.bodyXsmallRegular,
      bodyXsmallSemibold: bodyXsmallSemibold ?? this.bodyXsmallSemibold,
      bodyXsmallBold: bodyXsmallBold ?? this.bodyXsmallBold,
      bodyXsmallMedium: bodyXsmallMedium ?? this.bodyXsmallMedium,
      materialThemeDisplayLarge: materialThemeDisplayLarge ?? this.materialThemeDisplayLarge,
      materialThemeDisplayMedium: materialThemeDisplayMedium ?? this.materialThemeDisplayMedium,
      materialThemeDisplaySmall: materialThemeDisplaySmall ?? this.materialThemeDisplaySmall,
      materialThemeHeadlineLarge: materialThemeHeadlineLarge ?? this.materialThemeHeadlineLarge,
      materialThemeHeadlineMedium: materialThemeHeadlineMedium ?? this.materialThemeHeadlineMedium,
      materialThemeHeadlineSmall: materialThemeHeadlineSmall ?? this.materialThemeHeadlineSmall,
      materialThemeBodyLarge: materialThemeBodyLarge ?? this.materialThemeBodyLarge,
      materialThemeBodyMedium: materialThemeBodyMedium ?? this.materialThemeBodyMedium,
      materialThemeBodySmall: materialThemeBodySmall ?? this.materialThemeBodySmall,
      materialThemeLabelLarge: materialThemeLabelLarge ?? this.materialThemeLabelLarge,
      materialThemeLabelMedium: materialThemeLabelMedium ?? this.materialThemeLabelMedium,
      materialThemeLabelSmall: materialThemeLabelSmall ?? this.materialThemeLabelSmall,
      materialThemeTitleLarge: materialThemeTitleLarge ?? this.materialThemeTitleLarge,
      materialThemeTitleMedium: materialThemeTitleMedium ?? this.materialThemeTitleMedium,
      materialThemeTitleSmall: materialThemeTitleSmall ?? this.materialThemeTitleSmall,
    );
  }

  @override
  AppTextTheme lerp(AppTextTheme? other, double t) {
    if (other is! AppTextTheme) return this;
    return AppTextTheme(
      h1Bold: TextStyle.lerp(h1Bold, other.h1Bold, t),
      h2Bold: TextStyle.lerp(h2Bold, other.h2Bold, t),
      h3Bold: TextStyle.lerp(h3Bold, other.h3Bold, t),
      h4Bold: TextStyle.lerp(h4Bold, other.h4Bold, t),
      h5Bold: TextStyle.lerp(h5Bold, other.h5Bold, t),
      h6Bold: TextStyle.lerp(h6Bold, other.h6Bold, t),
      bodyXlargeRegular: TextStyle.lerp(bodyXlargeRegular, other.bodyXlargeRegular, t),
      bodyXlargeSemibold: TextStyle.lerp(bodyXlargeSemibold, other.bodyXlargeSemibold, t),
      bodyXlargeBold: TextStyle.lerp(bodyXlargeBold, other.bodyXlargeBold, t),
      bodyXlargeMedium: TextStyle.lerp(bodyXlargeMedium, other.bodyXlargeMedium, t),
      bodyLargeRegular: TextStyle.lerp(bodyLargeRegular, other.bodyLargeRegular, t),
      bodyLargeSemibold: TextStyle.lerp(bodyLargeSemibold, other.bodyLargeSemibold, t),
      bodyLargeBold: TextStyle.lerp(bodyLargeBold, other.bodyLargeBold, t),
      bodyLargeMedium: TextStyle.lerp(bodyLargeMedium, other.bodyLargeMedium, t),
      bodyMediumRegular: TextStyle.lerp(bodyMediumRegular, other.bodyMediumRegular, t),
      bodyMediumSemibold: TextStyle.lerp(bodyMediumSemibold, other.bodyMediumSemibold, t),
      bodyMediumBold: TextStyle.lerp(bodyMediumBold, other.bodyMediumBold, t),
      bodyMediumMedium: TextStyle.lerp(bodyMediumMedium, other.bodyMediumMedium, t),
      bodySmallRegular: TextStyle.lerp(bodySmallRegular, other.bodySmallRegular, t),
      bodySmallSemibold: TextStyle.lerp(bodySmallSemibold, other.bodySmallSemibold, t),
      bodySmallBold: TextStyle.lerp(bodySmallBold, other.bodySmallBold, t),
      bodySmallMedium: TextStyle.lerp(bodySmallMedium, other.bodySmallMedium, t),
      bodyXsmallRegular: TextStyle.lerp(bodyXsmallRegular, other.bodyXsmallRegular, t),
      bodyXsmallSemibold: TextStyle.lerp(bodyXsmallSemibold, other.bodyXsmallSemibold, t),
      bodyXsmallBold: TextStyle.lerp(bodyXsmallBold, other.bodyXsmallBold, t),
      bodyXsmallMedium: TextStyle.lerp(bodyXsmallMedium, other.bodyXsmallMedium, t),
      materialThemeDisplayLarge: TextStyle.lerp(materialThemeDisplayLarge, other.materialThemeDisplayLarge, t),
      materialThemeDisplayMedium: TextStyle.lerp(materialThemeDisplayMedium, other.materialThemeDisplayMedium, t),
      materialThemeDisplaySmall: TextStyle.lerp(materialThemeDisplaySmall, other.materialThemeDisplaySmall, t),
      materialThemeHeadlineLarge: TextStyle.lerp(materialThemeHeadlineLarge, other.materialThemeHeadlineLarge, t),
      materialThemeHeadlineMedium: TextStyle.lerp(materialThemeHeadlineMedium, other.materialThemeHeadlineMedium, t),
      materialThemeHeadlineSmall: TextStyle.lerp(materialThemeHeadlineSmall, other.materialThemeHeadlineSmall, t),
      materialThemeBodyLarge: TextStyle.lerp(materialThemeBodyLarge, other.materialThemeBodyLarge, t),
      materialThemeBodyMedium: TextStyle.lerp(materialThemeBodyMedium, other.materialThemeBodyMedium, t),
      materialThemeBodySmall: TextStyle.lerp(materialThemeBodySmall, other.materialThemeBodySmall, t),
      materialThemeLabelLarge: TextStyle.lerp(materialThemeLabelLarge, other.materialThemeLabelLarge, t),
      materialThemeLabelMedium: TextStyle.lerp(materialThemeLabelMedium, other.materialThemeLabelMedium, t),
      materialThemeLabelSmall: TextStyle.lerp(materialThemeLabelSmall, other.materialThemeLabelSmall, t),
      materialThemeTitleLarge: TextStyle.lerp(materialThemeTitleLarge, other.materialThemeTitleLarge, t),
      materialThemeTitleMedium: TextStyle.lerp(materialThemeTitleMedium, other.materialThemeTitleMedium, t),
      materialThemeTitleSmall: TextStyle.lerp(materialThemeTitleSmall, other.materialThemeTitleSmall, t),
    );
  }
}