name: animeverse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.2
  hugeicons: ^0.0.7

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon.png"
  android: true
  ios: true
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
