name: animeverse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.2
  hugeicons: ^0.0.7
  iconsax: ^0.0.8
  heroicons: ^0.10.0
  easy_date_timeline: ^1.1.3
  video_player: ^2.9.2
  chewie: ^1.8.5
  flutter_launcher_icons: ^0.14.1
  http: ^1.2.2
  shimmer: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon.png"
  android: true
  ios: true
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/no-release-date.png
