// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0w-w3MEMKfxtP7c0lXUtrN2o6x1CTHms',
    appId: '1:524245133632:web:a86c540d28dda1bccfb2a5',
    messagingSenderId: '524245133632',
    projectId: 'animeverse-b3925',
    authDomain: 'animeverse-b3925.firebaseapp.com',
    storageBucket: 'animeverse-b3925.appspot.com',
    measurementId: 'G-BWVXYYKCCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk0F_Oo7OYdlft-1f7THGzPE7yUf5-xd0',
    appId: '1:524245133632:android:2180bae6f360b5b8cfb2a5',
    messagingSenderId: '524245133632',
    projectId: 'animeverse-b3925',
    storageBucket: 'animeverse-b3925.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW3QomZf80YrGMtQzW8FnbbZvQk6zk1jQ',
    appId: '1:524245133632:ios:196c055c4f159e22cfb2a5',
    messagingSenderId: '524245133632',
    projectId: 'animeverse-b3925',
    storageBucket: 'animeverse-b3925.appspot.com',
    iosBundleId: 'com.example.animeverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW3QomZf80YrGMtQzW8FnbbZvQk6zk1jQ',
    appId: '1:524245133632:ios:196c055c4f159e22cfb2a5',
    messagingSenderId: '524245133632',
    projectId: 'animeverse-b3925',
    storageBucket: 'animeverse-b3925.appspot.com',
    iosBundleId: 'com.example.animeverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0w-w3MEMKfxtP7c0lXUtrN2o6x1CTHms',
    appId: '1:524245133632:web:05048fc32ba8ed64cfb2a5',
    messagingSenderId: '524245133632',
    projectId: 'animeverse-b3925',
    authDomain: 'animeverse-b3925.firebaseapp.com',
    storageBucket: 'animeverse-b3925.appspot.com',
    measurementId: 'G-F4S11DDVQD',
  );
}
